import React from "react";
import { Layout, Typography, Divider } from "antd";

const { Content } = Layout;
const { Title, Paragraph, Text, Link } = Typography;

export function TermsAndConditions() {
  return (
    <Layout style={{ background: "#fff", minHeight: "100vh" }}>
      <Content style={{ maxWidth: 900, margin: "0 auto", padding: "4rem 1.5rem" }}>
        <Typography>

          <Title level={1}>Terms & Conditions</Title>
          <Paragraph>Updated at 2026-01-08</Paragraph>

          <Title level={1}>General Terms</Title>
          <Paragraph>
            By accessing and placing an order with echoboxlogistics, you confirm
            that you are in agreement with and bound by the terms of service
            contained in the Terms & Conditions outlined below. These terms apply
            to the entire website and any email or other type of communication
            between you and echoboxlogistics.
          </Paragraph>
          <Paragraph>
            Under no circumstances shall echoboxlogistics team be liable for any
            direct, indirect, special, incidental or consequential damages,
            including, but not limited to, loss of data or profit, arising out of
            the use, or the inability to use, the materials on this site, even if
            echoboxlogistics team or an authorized representative has been advised
            of the possibility of such damages. If your use of materials from this
            site results in the need for servicing, repair or correction of
            equipment or data, you assume any costs thereof.
          </Paragraph>
          <Paragraph>
            echoboxlogistics will not be responsible for any outcome that may
            occur during the course of usage of our resources. We reserve the
            rights to change prices and revise the resources usage policy in any
            moment. This Terms & Conditions was created with{" "}
            <Link href="https://termify.io" target="_blank">
              Termify
            </Link>.
          </Paragraph>

          <Title level={1}>License</Title>
          <Paragraph>
            echoboxlogistics grants you a revocable, non-exclusive,
            non-transferable, limited license to download, install and use the
            website/app strictly in accordance with the terms of this Agreement.
          </Paragraph>
          <Paragraph>
            These Terms & Conditions are a contract between you and
            echoboxlogistics (referred to in these Terms & Conditions as
            &quot;echoboxlogistics&quot;, &quot;us&quot;, &quot;we&quot; or
            &quot;our&quot;), the provider of the echoboxlogistics website and the
            services accessible from the echoboxlogistics website (which are
            collectively referred to in these Terms & Conditions as the
            &quot;echoboxlogistics Service&quot;).
          </Paragraph>
          <Paragraph>
            You are agreeing to be bound by these Terms & Conditions. If you do
            not agree to these Terms & Conditions, please do not use the
            echoboxlogistics Service. In these Terms & Conditions, &quot;you&quot;
            refers both to you as an individual and to the entity you represent.
            If you violate any of these Terms & Conditions, we reserve the right
            to cancel your account or block access to your account without
            notice.
          </Paragraph>

          <Title level={1}>Definitions and key terms</Title>
          <Paragraph>
            To help explain things as clearly as possible in this Terms &
            Conditions, every time any of these terms are referenced, are
            strictly defined as:
          </Paragraph>
          <ul>
            <li>Cookie: small amount of data generated by a website and saved by your web browser.</li>
            <li>Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to echoboxlogistics.</li>
            <li>Country: where echoboxlogistics or the owners/founders of echoboxlogistics are based.</li>
            <li>Device: any internet connected device such as a phone, tablet, computer.</li>
            <li>Service: refers to the service provided by echoboxlogistics.</li>
            <li>Third-party service: advertisers, sponsors, promotional and marketing partners.</li>
            <li>Website: https://echoboxlogistics.com/</li>
            <li>You: a person or entity registered with echoboxlogistics.</li>
          </ul>

          <Title level={1}>Restrictions</Title>
          <Paragraph>You agree not to, and you will not permit others to:</Paragraph>
         <ul>
  <li>License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the website/app or make the platform available to any third party.</li>
  <li>Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the website/app.</li>
  <li>Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of echoboxlogistics or its affiliates, partners, suppliers or the licensors of the website/app.</li>
  </ul>

          <Title level={1}>Return and Refund Policy</Title>
          <Paragraph>
            Thanks for shopping at echoboxlogistics. We appreciate the fact that
            you like to buy the stuff we build.
          </Paragraph>
          <Paragraph>
            As with any shopping experience, there are terms and conditions that apply to transactions at echoboxlogistics. We’ll be as brief as our attorneys will allow. The main thing to remember is that by placing an order or making a purchase at echoboxlogistics, you agree to the terms along with echoboxlogistics's Privacy Policy.
          </Paragraph>
          <Paragraph>
            If, for any reason, You are not completely satisfied with a purchase We invite You to review our policy on refunds and returns. The policy is part of the Terms and Conditions governing Your purchase.
          </Paragraph>

          <Title level={1}>Your Suggestions</Title>
          <Paragraph>
          Any feedback, comments, ideas, improvements or suggestions (collectively, "Suggestions") provided by you to echoboxlogistics with respect to the website/app shall remain the sole and exclusive property of echoboxlogistics.
          
           echoboxlogistics shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or any compensation to you. 
          </Paragraph>

          <Title level={1}>Your Consent</Title>
          <Paragraph>
            We've updated our Terms & Conditions to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our website/app, registering an account, or making a purchase, you hereby consent to our Terms & Conditions.
          </Paragraph>

          <Title level={1}>Links to Other Websites</Title>
          <Paragraph>
           his Terms & Conditions applies only to the Services. The Services may contain links to other websites not operated or controlled by echoboxlogistics. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Terms & Conditions are no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.
          </Paragraph>

          <Title level={1}>Cookies</Title>
          <Paragraph>
            echoboxlogistics uses "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our website/app but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website/app as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.
          </Paragraph>

          <Title level={1}>Changes To Our Terms & Conditions</Title>
          <Paragraph>
           You acknowledge and agree that echoboxlogistics may stop (permanently or temporarily) providing the Service (or any features within the Service) to you or to users generally at  sole discretion, without prior notice to you. You may stop using the Service at any time. You do not need to specifically inform echoboxlogistics when you stop using the Service. You acknowledge and agree that if echoboxlogistics disables access to your account, you may be prevented from accessing the Service, your account details or any files or other materials which is contained in your account.
          
            If we decide to change our Terms & Conditions, we will post those changes on this page, and/or update the Terms & Conditions modification date below.
          </Paragraph>

          <Title level={1}>Modifications to Our website/app</Title>
  <Paragraph>echoboxlogistics reserves the right to modify, suspend or discontinue, temporarily or permanently, the website/app
  or any service to which it connects, with or without notice and without liability to you.</Paragraph>

  <Title level={1}>Updates to Our website/app</Title>
  <Paragraph>echoboxlogistics may from time to time provide enhancements or improvements to the features/ functionality of the website/app, which may include patches, bug fixes, updates, upgrades and other modifications ("Updates").</Paragraph>
  <Paragraph>Updates may modify or delete certain features and/or functionalities of the website/app. You agree that echoboxlogistics has no obligation to (i) provide any Updates, or (ii) continue to provide or enable any particular features and/or functionalities of the website/app to you.</Paragraph>
  <Paragraph>You further agree that all Updates will be (i) deemed to constitute an integral part of the website/app, and (ii) subject to the terms and conditions of this Agreement.</Paragraph>

  <Title level={1}>Third-Party Services</Title>
  <Paragraph>We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third- Party Services").</Paragraph>
  <Paragraph>You acknowledge and agree that echoboxlogistics shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. echoboxlogistics does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.</Paragraph>
  <Paragraph>Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.</Paragraph>

  <Title level={1}>Term and Termination</Title>
  <Paragraph>This Agreement shall remain in effect until terminated by you or echoboxlogistics.</Paragraph>
  <Paragraph>echoboxlogistics may, in its sole discretion, at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice.</Paragraph>
  <Paragraph>This Agreement will terminate immediately, without prior notice from echoboxlogistics, in the event that you fail to comply with any provision of this Agreement. You may also terminate this Agreement by deleting the website/app and all copies thereof from your computer.</Paragraph>
  <Paragraph>Upon termination of this Agreement, you shall cease all use of the website/app and delete all copies of the website/app from your computer.</Paragraph>
  <Paragraph>Termination of this Agreement will not limit any of echoboxlogistics's rights or remedies at law or in equity in case of breach by you (during the term of this Agreement) of any of your obligations under the present Agreement.</Paragraph>

  <Title level={1}>Copyright Infringement Notice</Title>
  <Paragraph>If you are a copyright owner or such owner’s agent and believe any material on our website/app constitutes an infringement on your copyright, please contact us setting forth the following information: (a) a physical or electronic signature of the copyright owner or a person authorized to act on his behalf; (b) identification of the material that is claimed to be infringing; (c) your contact information, including your address, telephone number, and an email; (d) a statement by you that you have a good faith belief that use of the material is not authorized by the copyright owners; and (e) the a statement that the information in the notification is accurate, and, under penalty of perjury you are authorized to act on behalf of the owner.</Paragraph>

  <Title level={1}>Indemnification</Title>
  <Paragraph>You agree to indemnify and hold echoboxlogistics and its parents, subsidiaries, affiliates, officers, employees, agents, partners and licensors (if any) harmless from any claim or demand, including reasonable attorneys' fees, due to or arising out of your: (a) use of the website/app; (b) violation of this Agreement or any law or regulation; or (c) violation of any right of a third party.</Paragraph>

  <Title level={1}>No Warranties</Title>
  <Paragraph>The website/app is provided to you "AS IS" and "AS AVAILABLE" and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, echoboxlogistics, on its own behalf and on behalf of its affiliates and its and their respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the website/app, including all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice. Without limitation to the foregoing, echoboxlogistics provides no warranty or undertaking, and makes no representation of any kind that the website/app will meet your requirements, achieve any intended results, be compatible or work with any other software, , systems or services, operate without interruption, meet any performance or reliability standards or be error free or that any errors or defects can or will be corrected.</Paragraph>
  <Paragraph>Without limiting the foregoing, neither echoboxlogistics nor any echoboxlogistics's provider makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the website/app, or the information, content, and materials or products included thereon; (ii) that the website/app will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content provided through the website/app; or (iv) that the website/app, its servers, the content, or e-mails sent from or on behalf of echoboxlogistics are free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful components.</Paragraph>
  <Paragraph>Some jurisdictions do not allow the exclusion of or limitations on implied warranties or the limitations on the applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to you.</Paragraph>

  <Title level={1}>Limitation of Liability</Title>
  <Paragraph>Notwithstanding any damages that you might incur, the entire liability of echoboxlogistics and any of its suppliers under any provision of this Agreement and your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by you for the website/app.</Paragraph>
  <Paragraph>To the maximum extent permitted by applicable law, in no event shall echoboxlogistics or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, damages for loss of profits, for loss of data or other information, for business interruption, for personal injury, for loss of privacy arising out of or in any way related to the use of or inability to use the website/app, third-party software and/or third-party hardware used with the website/app, or otherwise in connection with any provision of this Agreement), even if echoboxlogistics or any supplier has been advised of the possibility of such damages and even if the remedy fails of its essential purpose.</Paragraph>
  <Paragraph>Some states/jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you.</Paragraph>

  <Title level={1}>Severability</Title>
  <Paragraph>If any provision of this Agreement is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.</Paragraph>
  <Paragraph>This Agreement, together with the Privacy Policy and any other legal notices published by echoboxlogistics on the Services, shall constitute the entire agreement between you and echoboxlogistics concerning the Services. If any provision of this Agreement is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of this Agreement, which shall remain in full force and effect. No waiver of any term of this Agreement shall be deemed a further or continuing waiver of such term or any other term, and echoboxlogistics's failure to assert any right or provision under this Agreement shall not constitute a waiver of such right or provision. YOU AND echoboxlogistics AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE SERVICES MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.</Paragraph>

  <Title level={1}>Waiver</Title>
  <Paragraph>Except as provided herein, the failure to exercise a right or to require performance of an obligation under this Agreement shall not effect a party's ability to exercise such right or require such performance at any time thereafter nor shall be the waiver of a breach constitute waiver of any subsequent breach.</Paragraph>
  <Paragraph>o failure to exercise, and no delay in exercising, on the part of either party, any right or any power under this Agreement shall operate as a waiver of that right or power. Nor shall any single or partial exercise of any right or power under this Agreement preclude further exercise of that or any other right granted herein. In the event of a conflict between this Agreement and any applicable purchase or other terms, the terms of this Agreement shall govern.</Paragraph>

  <Title level={1}>Amendments to this Agreement</Title>
  <Paragraph>echoboxlogistics reserves the right, at its sole discretion, to modify or replace this Agreement at any time. If a revision is material we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</Paragraph>
  <Paragraph>By continuing to access or use our website/app after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use echoboxlogistics.</Paragraph>

  <Title level={1}>Entire Agreement</Title>
  <Paragraph>The Agreement constitutes the entire agreement between you and echoboxlogistics regarding your use of the website/app and supersedes all prior and contemporaneous written or oral agreements between you and echoboxlogistics.</Paragraph>
  <Paragraph>You may be subject to additional terms and conditions that apply when you use or purchase other echoboxlogistics's  services, which echoboxlogistics will provide to you at the time of such use or purchase.</Paragraph>

  <Title level={1}>Updates to Our Terms</Title>
  <Paragraph>We may change our Service and policies, and we may need to make changes to these Terms so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to these Terms and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Terms. If you do not want to agree to these or any updated Terms, you can delete your account.</Paragraph>

  <Title level={1}>Intellectual Property</Title>
  <Paragraph>The website/app and its entire contents, features and functionality (including but not limited to all information, software, text, displays, images, video and audio, and the design, selection and arrangement thereof), are owned by echoboxlogistics, its licensors or other providers of such material and are protected by  and international copyright, trademark, patent, trade secret and other intellectual property or proprietary rights laws. The material may not be copied, modified, reproduced, downloaded or distributed in any way, in whole or in part, without the express prior written permission of echoboxlogistics, unless and except as is expressly provided in these Terms & Conditions. Any unauthorized use of the material is prohibited.</Paragraph>

  <Title level={1}>Agreement to Arbitrate</Title>
  <Paragraph>This section applies to any dispute EXCEPT IT DOESN’T INCLUDE A DISPUTE RELATING TO CLAIMS FOR INJUNCTIVE OR EQUITABLE RELIEF REGARDING THE ENFORCEMENT OR VALIDITY OF YOUR OR echoboxlogistics's INTELLECTUAL PROPERTY RIGHTS. The term “dispute” means any dispute, action, or other controversy between you and echoboxlogistics concerning the Services or this agreement, whether in contract, warranty, tort, statute, regulation, ordinance, or any other legal or equitable basis. “Dispute” will be given the broadest possible meaning allowable under law.</Paragraph>

  <Title level={1}>Notice of Dispute</Title>
  <Paragraph>In the event of a dispute, you or echoboxlogistics must give the other a Notice of Dispute, which is a written statement that sets forth the name, address, and contact information of the party giving it, the facts giving rise to the dispute, and the relief requested. You must send any Notice of Dispute via email to: <Link href="mailto:support@echoboxlogistics.com">
                support@echoboxlogistics.com
              </Link>. echoboxlogistics will send any Notice of Dispute to you by mail to your address if we have it, or otherwise to your email address. You and echoboxlogistics will attempt to resolve any dispute through informal negotiation within sixty (60) days from the date the Notice of Dispute is sent. After sixty (60) days, you or echoboxlogistics may commence arbitration.</Paragraph>

  <Title level={1}>Binding Arbitration</Title>
  <Paragraph>If you and echoboxlogistics don’t resolve any dispute by informal negotiation, any other effort to resolve the dispute will be conducted exclusively by binding arbitration as described in this section. You are giving up the right to litigate (or participate in as a party or class member) all disputes in court before a judge or jury. The dispute shall be settled by binding arbitration in accordance with the commercial arbitration rules of the American Arbitration Association. Either party may seek any interim or preliminary injunctive relief from any court of competent jurisdiction, as necessary to protect the party’s rights or property pending the completion of arbitration. Any and all legal, accounting, and other costs, fees, and expenses incurred by the prevailing party shall be borne by the non-prevailing party.</Paragraph>

  <Title level={1}>Submissions and Privacy</Title>
  <Paragraph>In the event that you submit or post any ideas, creative suggestions, designs, photographs, information, advertisements, data or proposals, including ideas for new or improved products, services, features, technologies or promotions, you expressly agree that such submissions will automatically be treated as non-confidential and non-proprietary and will become the sole property of echoboxlogistics without any compensation or credit to you whatsoever. echoboxlogistics and its affiliates shall have no obligations with respect to such submissions or posts and may use the ideas contained in such submissions or posts for any purposes in any medium in perpetuity, including, but not limited to, developing, manufacturing, and marketing products and services using such ideas.</Paragraph>

  <Title level={1}>Promotions</Title>
  <Paragraph>echoboxlogistics may, from time to time, include contests, promotions, sweepstakes, or other activities (“Promotions”) that require you to submit material or information concerning yourself. Please note that all Promotions may be governed by separate rules that may contain certain eligibility requirements, such as restrictions as to age and geographic location. You are responsible to read all Promotions rules to determine whether or not you are eligible to participate. If you enter any Promotion, you agree to abide by and to comply with all Promotions Rules.</Paragraph>
  <Paragraph>Additional terms and conditions may apply to purchases of goods or services on or through the Services, which terms and conditions are made a part of this Agreement by this reference.</Paragraph>

  <Title level={1}>Typographical Errors</Title>
  <Paragraph>In the event a product and/or service is listed at an incorrect price or with incorrect information due to typographical error, we shall have the right to refuse or cancel any orders placed for the product and/or service listed at the incorrect price. We shall have the right to refuse or cancel any such order whether or not the order has been confirmed and your credit card charged. If your credit card has already been charged for the purchase and your order is canceled, we shall immediately issue a credit to your credit card account or other payment account in the amount of the charge.</Paragraph>

  <Title level={1}>Miscellaneous</Title>
  <Paragraph>If for any reason a court of competent jurisdiction finds any provision or portion of these Terms & Conditions to be unenforceable, the remainder of these Terms & Conditions will continue in full force and effect. Any waiver of any provision of these Terms & Conditions will be effective only if in writing and signed by an authorized representative of echoboxlogistics. echoboxlogistics will be entitled to injunctive or other equitable relief (without the obligations of posting any bond or surety) in the event of any breach or anticipatory breach by you. echoboxlogistics operates and controls the echoboxlogistics Service from its offices in . The Service is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation. Accordingly, those persons who choose to access the echoboxlogistics Service from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable. These Terms & Conditions (which include and incorporate the echoboxlogistics Privacy Policy) contains the entire understanding, and supersedes all prior understandings, between you and echoboxlogistics concerning its subject matter, and cannot be changed or modified by you. The section headings used in this Agreement are for convenience only and will not be given any legal import.</Paragraph>

  <Title level={1}>Disclaimer</Title>
  <Paragraph>echoboxlogistics is not responsible for any content, code or any other imprecision.</Paragraph>
  <Paragraph>echoboxlogistics does not provide warranties or guarantees.</Paragraph>
  <Paragraph>In no event shall echoboxlogistics be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. The Company reserves the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.</Paragraph>
  <Paragraph>The echoboxlogistics Service and its contents are provided "as is" and "as available" without any warranty or representations of any kind, whether express or implied. echoboxlogistics is a distributor and not a publisher of the content supplied by third parties; as such, echoboxlogistics exercises no editorial control over such content and makes no warranty or representation as to the accuracy, reliability or currency of any information, content, service or merchandise provided through or accessible via the echoboxlogistics Service. Without limiting the foregoing, echoboxlogistics specifically disclaims all warranties and representations in any content transmitted on or in connection with the echoboxlogistics Service or on sites that may appear as links on the echoboxlogistics Service, or in the products provided as a part of, or otherwise in connection with, the echoboxlogistics Service, including without limitation any warranties of merchantability, fitness for a particular purpose or non-infringement of third party rights. No oral advice or written information given by echoboxlogistics or any of its affiliates, employees, officers, directors, agents, or the like will create a warranty. Price and availability information is subject to change without notice. Without limiting the foregoing, echoboxlogistics does not warrant that the echoboxlogistics Service will be uninterrupted, uncorrupted, timely, or error-free.</Paragraph>

          <Title level={1}>Contact Us</Title>
          <Paragraph>
            Don&apos;t hesitate to contact us if you have any questions.
          </Paragraph>
          <ul>
            <li>
              Via Email:{" "}
              <Link href="mailto:support@echoboxlogistics.com">
                support@echoboxlogistics.com
              </Link>
            </li>
          </ul>

        </Typography>
      </Content>
    </Layout>
  );
}

export default TermsAndConditions;
